## Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:",x)
print("Test if none of the elements of the said array is zero\n:",np.all(x))
y = np.array([0, 1, 2, 3])
print("Original array:",y)
print("Test if none of the elements of the said array is zero:\n",np.all(y))

Original array: [1 2 3 4]
Test if none of the elements of the said array is zero
: True
Original array: [0 1 2 3]
Test if none of the elements of the said array is zero:
 False


## Write a NumPy program to create an array of 5 zeros, 5 ones, 5 fives.

In [8]:
import numpy as np
a=np.zeros(5, dtype=int)
b=np.ones(5, dtype=int)
c=np.ones(5, dtype=int)*5
z=np.concatenate((a,b,c),axis=0).reshape(3,5)
z

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5]])

## Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [9]:
import numpy as np
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[ 0.40688422  0.46928635  0.56078528  0.85336102 -0.08575531 -1.62001133
 -0.16431504  0.28718075  0.02080505  0.07641035  0.25687998  1.13592491
 -0.46978738 -2.55733841  0.47457803]


## Write a NumPy program to create a vector with values ranging from 10 to 40 and print all values except the first and last.

In [11]:
import numpy as np
a = np.arange(10,40)
z = a[1:]
z

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

## Write a NumPy program to create a vector with values from 1 to 15 and change the sign of the numbers in the range from 10 to 15. 

In [12]:
import numpy as np
x = np.arange(15)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 10) & (x <= 15)] *= -1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14]


## Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [13]:
import numpy as np
a= np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


## Write a NumPy program to compute the inner product of two given vectors

In [14]:
import numpy as np
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


## Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [15]:
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))    

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


## Write a NumPy program to add, subtract, multiply, divide arguments element-wise. 


In [16]:
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))

Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


## Write a NumPy program to get the minimum and maximum value of a given array along the second axis.

In [17]:
import numpy as np
x = np.arange(4).reshape((2, 2))
print("\nOriginal array:")
print(x)
print("\nMaximum value along the second axis:")
print(np.amax(x, 1))
print("Minimum value along the second axis:")
print(np.amin(x, 1))


Original array:
[[0 1]
 [2 3]]

Maximum value along the second axis:
[1 3]
Minimum value along the second axis:
[0 2]


## Write a NumPy program to display all the dates for the month of May, 2019

In [18]:
import numpy as np
print("May, 2019")
print(np.arange('2019-05', '2019-06', dtype='datetime64[D]'))

May, 2019
['2019-05-01' '2019-05-02' '2019-05-03' '2019-05-04' '2019-05-05'
 '2019-05-06' '2019-05-07' '2019-05-08' '2019-05-09' '2019-05-10'
 '2019-05-11' '2019-05-12' '2019-05-13' '2019-05-14' '2019-05-15'
 '2019-05-16' '2019-05-17' '2019-05-18' '2019-05-19' '2019-05-20'
 '2019-05-21' '2019-05-22' '2019-05-23' '2019-05-24' '2019-05-25'
 '2019-05-26' '2019-05-27' '2019-05-28' '2019-05-29' '2019-05-30'
 '2019-05-31']


## Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array

In [20]:
import numpy as np
x = ['ml', 'pYtHON', 'Data science', 'Numpy']
print("Original Array:")
print(str(x))

lowered_case = np.char.lower(str(x))
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)

print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['ml', 'pYtHON', 'Data science', 'Numpy']
Lowered:  ['ml', 'python', 'data science', 'numpy']
Uppered:  ['ML' 'PYTHON' 'DATA SCIENCE' 'NUMPY']
Swapcased:  ['ML' 'PyThon' 'dATA SCIENCE' 'nUMPY']
Titlecased:  ['Ml' 'Python' 'Data Science' 'Numpy']
