In [2]:
import numpy as np

In [2]:
# check numpy version
np.__version__

'1.23.4'

#### *Converting tuple to ndarray*

In [4]:
a = (1,2,3,4,5)
a

(1, 2, 3, 4, 5)

In [5]:
type(a)

tuple

In [6]:
b = np.array(a)
print(b)

[1 2 3 4 5]


In [7]:
type(b)

numpy.ndarray

#### *Converting list to ndarray*

In [8]:
x = [5,6,7,8]
x

[5, 6, 7, 8]

In [9]:
type(x)

list

In [10]:
y = np.array(x)
y

array([5, 6, 7, 8])

In [11]:
type(y)

numpy.ndarray

#### *Speed Comparision*

In [12]:
import time 
import numpy as np
size_1=1000000
def pure_python_version():
    time_python =time.time()
    list1=range(size_1)
    list2=range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    return time.time() - time_python

def numpy_version():
    time_numpy = time.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    return time.time() - time_numpy
python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",format(python_time))
print("numpy =",format(numpy_time))

pure python version= 0.4278557300567627
numpy = 0.003950595855712891


#### *Creating array*

In [5]:
my_list = [2,3,4,6,7,8]

In [6]:
my_list

[2, 3, 4, 6, 7, 8]

In [7]:
my_list = [2,3,4,5,6,7,8, 'Numpy']

In [8]:
my_list

[2, 3, 4, 5, 6, 7, 8, 'Numpy']

In [10]:
my_array = np.array(my_list)
my_array

array(['2', '3', '4', '5', '6', '7', '8', 'Numpy'], dtype='<U11')

#### *Convert nested list to an array*
-- converting nested list to array for faster computation/processing 

In [3]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]

In [4]:
type(array_2)

list

In [5]:
# coverting nested list to array
nestd_list_to_array = np.array(array_2)
nestd_list_to_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(nestd_list_to_array)

numpy.ndarray

#### *ndim - ndimensional*

In [7]:
a = np.array([1, 2, 3,7,5,1], ndmin = 4) 
print (a)
np.ndim(a)

[[[[1 2 3 7 5 1]]]]


4

#### *dtype - data_type*
1. *complex - return the array in complex number format*
2. *str - return the array in string format*

In [11]:
a = [1,2,3]
a

[1, 2, 3]

In [14]:
b = np.array(a, dtype = complex)
print(b)

[1.+0.j 2.+0.j 3.+0.j]


In [13]:
b.dtype

dtype('complex128')

In [15]:
c = np.array(a, dtype = str)
print(c)

['1' '2' '3']


In [16]:
c.dtype

dtype('<U1')

#### *len*

In [17]:
array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Here, The output results to 3 not 9 because we are passing 3 lists inisde a list

In [18]:
len(array_3)

3

#### *Indexing & Slicing*

In [19]:
array_3[2] #Indexing 3rd row

array([7, 8, 9])

In [20]:
array_3[1][-1] # accessiing '6'

6

In [21]:
#Accessing 2nd column
array_3[:,1]

array([2, 5, 8])

In [22]:
#Accessing 2nd row
array_3[2,:]

array([7, 8, 9])

In [23]:
array_3[1:3,2:3]

array([[6],
       [9]])

#### *Array Attributes*

In [24]:
# no. of rows and no. of columns 
array_3.shape 

(3, 3)

In [25]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
array_3.ndim

2

In [27]:
array_3.dtype

dtype('int32')

#### *Array Initialization*

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [36]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [38]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
#show 10 equally space values between  0 to 4
np.linspace(0,4,10) #(start,end,no of values)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [41]:
np.linspace(3,4,10)

array([3.        , 3.11111111, 3.22222222, 3.33333333, 3.44444444,
       3.55555556, 3.66666667, 3.77777778, 3.88888889, 4.        ])

In [42]:
np.linspace(3,4,10).reshape(5,2)

array([[3.        , 3.11111111],
       [3.22222222, 3.33333333],
       [3.44444444, 3.55555556],
       [3.66666667, 3.77777778],
       [3.88888889, 4.        ]])

In [44]:
np.eye(4,4, dtype=int) #Identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [28]:
np.linspace(0,4,10) # (start,end,no of values)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [29]:
np.linspace(3,4,10)

array([3.        , 3.11111111, 3.22222222, 3.33333333, 3.44444444,
       3.55555556, 3.66666667, 3.77777778, 3.88888889, 4.        ])

In [31]:
np.linspace(3,4,10).reshape(5,2)

array([[3.        , 3.11111111],
       [3.22222222, 3.33333333],
       [3.44444444, 3.55555556],
       [3.66666667, 3.77777778],
       [3.88888889, 4.        ]])

#### *Array Initilization with Random numbers*

In [45]:
np.random.rand(3)

array([0.46589247, 0.55236477, 0.5765105 ])

In [46]:
np.random.randint(100)

10

In [48]:
np.random.randint(1,100000)

86855

In [49]:
np.random.rand(2,3)

array([[0.32547684, 0.93973112, 0.14337644],
       [0.16102195, 0.40797322, 0.28945275]])

In [33]:
np.eye(3,3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [34]:
np.arange(2,2,16)

array([], dtype=int32)

In [35]:
np.arange(2,5,16)

array([2])

In [36]:
np.arange(2,40,16)

array([ 2, 18, 34])

#### *Statistical Functions*

In [38]:
a = [[1,2,3],[4,5,6],[7,8,9]]
z = np.array(a)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
z.min()

1

In [40]:
z.max()

9

In [41]:
z.mean()

5.0

In [42]:
z.argmax()

8

In [43]:
z.argmin()

0

In [44]:
z.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [45]:
z.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [46]:
# convert 2d to 1d
z.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
z.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### *Maths*

In [49]:
import numpy as np
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print("Adding to arrays: ")
print(A + B)
print("Substracting Two Arrays")
print(A-B)
print("\nMultiplying two arrays: ")
print(A * B)
print("Multiplying one Array with scalar")
print(3*A)
print("Matrix Multiplication")
print(np.dot (A,B))

Adding to arrays: 
[[ 5. 11. 12.]
 [22. 23. 24.]
 [32. 33. 34.]]
Substracting Two Arrays
[[ 3.  9. 10.]
 [20. 21. 22.]
 [30. 31. 32.]]

Multiplying two arrays: 
[[ 4. 10. 11.]
 [21. 22. 23.]
 [31. 32. 33.]]
Multiplying one Array with scalar
[[12 30 33]
 [63 66 69]
 [93 96 99]]
Matrix Multiplication
[[25. 25. 25.]
 [66. 66. 66.]
 [96. 96. 96.]]


In [53]:
#square root
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [54]:
#exponential
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [55]:
a = np.array([0,30,45,60,90]) 

print ('Sine of different angles:' )
# Convert to radians by multiplying with pi/180 
print (np.sin(a*np.pi/180) )
print ("\n") 

print ('Cosine values for angles in array:')
print (np.cos(a*np.pi/180) )
print ("\n") 

print ('Tangent values for given angles:' )
print (np.tan(a*np.pi/180) )

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [56]:
a=np.array([[11.667,23.662],[33.21,45.887]])
print(a)
print (np.around(a)) 
print (np.around(a, decimals = 1))
print (np.around(a, decimals = 2))

[[11.667 23.662]
 [33.21  45.887]]
[[12. 24.]
 [33. 46.]]
[[11.7 23.7]
 [33.2 45.9]]
[[11.67 23.66]
 [33.21 45.89]]


#### *Concatenating Arrays*
1.  *axis = 0 -> row wise concatenation*
2.  *axis = 1 -> column wise concatenation*

In [57]:
A=[[1,2,3],[3,4,5]]
B=[[3,3,4],[1,2,0]]
a=np.array(A)
b=np.array(B)

In [58]:
a,b

(array([[1, 2, 3],
        [3, 4, 5]]),
 array([[3, 3, 4],
        [1, 2, 0]]))

In [59]:
np.concatenate((a,b)) 

array([[1, 2, 3],
       [3, 4, 5],
       [3, 3, 4],
       [1, 2, 0]])

In [61]:
np.concatenate((a,b), axis = 0)

array([[1, 2, 3],
       [3, 4, 5],
       [3, 3, 4],
       [1, 2, 0]])

In [62]:
np.concatenate((a,b), axis = 1)

array([[1, 2, 3, 3, 3, 4],
       [3, 4, 5, 1, 2, 0]])